version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "8000:8000"
    volumes:
      - '.:/opt/app'
#    command: ["make", "up"]